### ISSUE TITLE
preload_base.js missing in live demo

### ISSUE THREAD

**Issue by skinhat** [kripken/BananaBread#63]
When I run the arena demo at 
https://kripken.github.io/BananaBread/cube2/index.html
I get the error that it cannot find https://kripken.github.io/BananaBread/cube2/game/preload_base.js 

When I look at the repository this file is not there.

**Comment by kripken** [comment]
Yes, I did some cleanups in preparation for a demo that is both asm.js and wasm, which is runnable here: https://kripken.github.io/BananaBread/wasm-demo/

We should probably update the readme and maybe remove the old index.html

**Comment by kripken** [comment]
Updated old html, added redirect.
