### ISSUE TITLE
live demo doesn't work anymore 

### ISSUE THREAD

**Issue by BluesparkYT** [kripken/BananaBread#64]
you cant find the game anymore unless you use the archive machine also when it did work a bit ago it was one of the first versions of the game

**Comment by kripken** [comment]
Thanks, I've updated the demo and forgot to fix the link. Fixed now (points to https://kripken.github.io/BananaBread/cube2/bb.html ).

**Comment by kripken** [comment]
I also made it use wasm. Perhaps we should also keep around an asm.js version?

**Comment by fsvieira** [comment]
On my browser there is a error:

Failed to load resource: the server responded with a status of 404 (Not Found)

Its trying to fetch https://kripken.github.io/BananaBread/cube2/game/gl-matrix.js.js 
And it probably should be https://kripken.github.io/BananaBread/cube2/game/gl-matrix.js

**Comment by kripken** [comment]
Thanks, fixed.
